"""CommunityCrossFeeding — two-panel niche-differentiation figure for the
two-species community composite.

Top panel: per-species biomass (glucose vs acetate specialist).
Bottom panel: the shared glucose and acetate pools.
The two growth phases are shaded and the glucose-exhaustion / acetate-overflow
events are annotated, so a reviewer sees cross-feeding (not competition) at a
glance: the acetate specialist blooms *after* the acetate pool peaks.

Generated by /viva-viz on 2026-09-26 from request 'community-cross-feeding'.
"""
from __future__ import annotations
import json
from process_bigraph.visualization import as_visualization


# Colors reused by series across the study's charts.
_C = {
    "glucose_sp": "#2563eb",   # glucose specialist — blue
    "acetate_sp": "#f59e0b",   # acetate specialist — amber
    "glucose": "#16a34a",      # glucose pool — green
    "acetate": "#dc2626",      # acetate pool — red
    "phase1": "rgba(37,99,235,0.06)",
    "phase2": "rgba(245,158,11,0.07)",
}


def _peak_index(ys):
    return max(range(len(ys)), key=lambda i: ys[i]) if ys else 0


@as_visualization(
    inputs={
        "time": "list[float]",
        "glucose_specialist": "list[float]",
        "acetate_specialist": "list[float]",
        "glucose": "list[float]",
        "acetate": "list[float]",
    },
    name="CommunityCrossFeeding",
    demo={
        "time": [0.0, 2.5, 5.0, 7.5, 10.0, 12.5, 15.0, 17.5, 20.0, 22.5,
                 25.0, 27.5, 30.0, 32.5, 35.0],
        "glucose_specialist": [0.008, 0.032, 0.128, 0.509, 0.763, 0.790, 0.818,
                               0.845, 0.872, 0.897, 0.919, 0.930, 0.930, 0.930, 0.930],
        "acetate_specialist": [0.002, 0.003, 0.005, 0.009, 0.012, 0.016, 0.022,
                               0.030, 0.041, 0.055, 0.074, 0.098, 0.111, 0.111, 0.111],
        "glucose": [15.0, 14.49, 12.47, 4.56, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0],
        "acetate": [0.0, 0.57, 2.88, 12.08, 16.11, 14.19, 12.16, 10.02, 7.75,
                    5.37, 2.93, 0.73, 0.01, 0.01, 0.01],
    },
)
def update_community_cross_feeding(state):
    """Two stacked panels: per-species biomass (top) and shared pools (bottom)."""
    t = list(state["time"])
    gs = list(state["glucose_specialist"])
    ac = list(state["acetate_specialist"])
    glc = list(state["glucose"])
    acet = list(state["acetate"])

    # Event markers derived from the data: acetate overflow peak + glucose
    # exhaustion (first time glucose falls below a small epsilon).
    pk = _peak_index(acet)
    t_peak, acet_peak = (t[pk], acet[pk]) if acet else (0.0, 0.0)
    t_glc0 = next((t[i] for i in range(len(glc)) if glc[i] <= 0.05), t_peak)
    t_end = t[-1] if t else 1.0

    traces = [
        # Top panel (yaxis 'y') — biomass
        {"x": t, "y": gs, "type": "scatter", "mode": "lines", "yaxis": "y",
         "name": "glucose specialist", "line": {"color": _C["glucose_sp"], "width": 2.6},
         "hovertemplate": "t=%{x:.1f}<br>biomass=%{y:.3f} gDW<extra>glucose sp.</extra>"},
        {"x": t, "y": ac, "type": "scatter", "mode": "lines", "yaxis": "y",
         "name": "acetate specialist", "line": {"color": _C["acetate_sp"], "width": 2.6},
         "hovertemplate": "t=%{x:.1f}<br>biomass=%{y:.3f} gDW<extra>acetate sp.</extra>"},
        # Bottom panel (yaxis 'y2') — shared pools
        {"x": t, "y": glc, "type": "scatter", "mode": "lines", "yaxis": "y2",
         "name": "glucose pool", "line": {"color": _C["glucose"], "width": 2.2},
         "hovertemplate": "t=%{x:.1f}<br>glucose=%{y:.2f} mM<extra></extra>"},
        {"x": t, "y": acet, "type": "scatter", "mode": "lines", "yaxis": "y2",
         "name": "acetate pool", "line": {"color": _C["acetate"], "width": 2.2},
         "fill": "tozeroy", "fillcolor": "rgba(220,38,38,0.08)",
         "hovertemplate": "t=%{x:.1f}<br>acetate=%{y:.2f} mM<extra></extra>"},
        # Acetate-peak marker on the bottom panel
        {"x": [t_peak], "y": [acet_peak], "type": "scatter", "mode": "markers",
         "yaxis": "y2", "name": "acetate peak", "showlegend": False,
         "marker": {"color": _C["acetate"], "size": 9, "symbol": "circle-open", "line": {"width": 2}},
         "hovertemplate": "acetate peak %{y:.1f} mM at t=%{x:.1f}<extra></extra>"},
    ]

    # Phase shading (spans both panels via yref 'paper') + the glucose-exhaustion divider.
    shapes = [
        {"type": "rect", "xref": "x", "yref": "paper", "x0": 0, "x1": t_glc0,
         "y0": 0, "y1": 1, "fillcolor": _C["phase1"], "line": {"width": 0}, "layer": "below"},
        {"type": "rect", "xref": "x", "yref": "paper", "x0": t_glc0, "x1": t_end,
         "y0": 0, "y1": 1, "fillcolor": _C["phase2"], "line": {"width": 0}, "layer": "below"},
        {"type": "line", "xref": "x", "yref": "paper", "x0": t_glc0, "x1": t_glc0,
         "y0": 0, "y1": 1, "line": {"color": "#64748b", "dash": "dash", "width": 1}},
    ]
    annotations = [
        {"x": t_glc0, "y": 1.0, "xref": "x", "yref": "paper", "yanchor": "bottom",
         "text": f"glucose exhausted (t≈{t_glc0:.1f})", "showarrow": False,
         "font": {"size": 11, "color": "#475569"}},
        {"x": t_glc0 / 2, "y": 0.5, "xref": "x", "yref": "paper", "showarrow": False,
         "text": "① glucose-driven bloom", "font": {"size": 11, "color": _C["glucose_sp"]}},
        {"x": (t_glc0 + t_end) / 2, "y": 0.5, "xref": "x", "yref": "paper", "showarrow": False,
         "text": "② acetate cross-feeding bloom", "font": {"size": 11, "color": _C["acetate_sp"]}},
        {"x": t_peak, "y": acet_peak, "xref": "x", "yref": "y2", "yanchor": "bottom",
         "ax": 24, "ay": -22, "text": f"acetate overflow ≈{acet_peak:.1f} mM",
         "font": {"size": 10, "color": _C["acetate"]}, "arrowcolor": _C["acetate"], "arrowhead": 2},
    ]

    layout = {
        "title": {"text": "Two-species cross-feeding: the acetate specialist blooms on the "
                          "glucose specialist's overflow", "font": {"size": 14}},
        "shapes": shapes,
        "annotations": annotations,
        "margin": {"l": 60, "r": 20, "t": 50, "b": 45},
        "xaxis": {"title": {"text": "time (a.u.)"}, "anchor": "y2", "domain": [0, 1]},
        "yaxis": {"title": {"text": "biomass (gDW)"}, "domain": [0.56, 1.0]},
        "yaxis2": {"title": {"text": "shared pool (mM)"}, "domain": [0.0, 0.44]},
        "legend": {"orientation": "h", "y": -0.16, "x": 0.5, "xanchor": "center"},
        "hovermode": "x unified",
        "plot_bgcolor": "white",
    }

    caption = ("Top: per-species biomass. Bottom: the shared glucose (green) and acetate (red) "
               "pools. The glucose specialist blooms first and overflows acetate; once glucose is "
               "exhausted the acetate specialist blooms on that byproduct — niche differentiation "
               "by cross-feeding, not competition.")

    return {"html": (
        '<div id="viz" style="height:460px"></div>'
        '<p style="font:12px/1.5 system-ui,sans-serif;color:#475569;margin:6px 10px 0">'
        + caption +
        '</p>'
        '<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>'
        '<script>Plotly.newPlot("viz",'
        + json.dumps(traces) + ',' + json.dumps(layout)
        + ', {responsive:true, displayModeBar:false});</script>'
    )}
